apiVersion: v1
kind: Service
metadata:
  name: pres-gateway
  namespace: planara
spec:
  type: ClusterIP
  selector:
    app: pres-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080